# Generated by Django 2.2.5 on 2019-09-24 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField(null=True)),
                ('claps', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog_category',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blog_category',
            name='category',
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.BlogPost'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Blog_category',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
