# Generated by Django 2.2.5 on 2019-09-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
    ]
